/*
 * Code generated by protoc-gen-pbrpc. DO NOT EDIT.
 * source: services.proto
 */

package sample

import (
    "context"
    "reflect"

    pbrpc "github.com/let-z-go/pbrpc"
)

// ClientService ///////////////////////////////////////////////////////////////

const (
    ClientServiceName = "Client"

    ClientService_GetNickname = 0
)

type ClientServiceClient struct {
    methodCaller pbrpc.MethodCaller
    extraData    []byte
    autoRetry    bool
}

func (self ClientServiceClient) GetNickname(context_ context.Context) (*GetNicknameResponse, error) {
    _ = pbrpc.IncomingMessage(&GetNicknameResponse{})
    methodRecord := &methodTableOfClientService[ClientService_GetNickname]
    response, e := self.methodCaller.CallMethod(context_, ClientServiceName, methodRecord.Name, methodRecord.Index, self.extraData, &pbrpc.Void{}, methodRecord.ResponseType, self.autoRetry)

    if e != nil {
        return nil, e
    }

    return response.(*GetNicknameResponse), e
}

func (self ClientServiceClient) WithAutoRetry(autoRetry bool) ClientServiceClient {
    return ClientServiceClient{
        methodCaller: self.methodCaller,
        extraData: self.extraData,
        autoRetry: autoRetry,
    }
}

func (self ClientServiceClient) WithExtraData(extraData []byte) ClientServiceClient {
    return ClientServiceClient{
        methodCaller: self.methodCaller,
        extraData: extraData,
        autoRetry: self.autoRetry,
    }
}

func MakeClientServiceClient(methodCaller pbrpc.MethodCaller) ClientServiceClient {
    return ClientServiceClient{
        methodCaller: methodCaller,
        extraData: nil,
        autoRetry: false,
    }
}

type ClientServiceHandlerBase struct {}

func (ClientServiceHandlerBase) X_GetName() string { return ClientServiceName }
func (ClientServiceHandlerBase) X_GetMethodTable() pbrpc.MethodTable { return methodTableOfClientService }

// `ClientServiceHandler` template:
//
// type ClientServiceHandler struct {
//     ClientServiceHandlerBase
// }
//
// func (ClientServiceHandler) GetNickname(context_ context.Context) (*GetNicknameResponse, error)

var methodTableOfClientService = pbrpc.MethodTable{
    ClientService_GetNickname: {
        ClientService_GetNickname,
        "GetNickname",
        reflect.TypeOf(pbrpc.Void{}),
        reflect.TypeOf(GetNicknameResponse{}),

        func(serviceHandler pbrpc.ServiceHandler, context_ context.Context, _ interface{}) (pbrpc.OutgoingMessage, error) {
            methodHandler, ok := serviceHandler.(interface { GetNickname(context.Context) (*GetNicknameResponse, error) })

            if !ok {
                return nil, pbrpc.MakeError(pbrpc.ErrorNotImplemented)
            }

            return methodHandler.GetNickname(context_)
        },
    },
}

// ServerService ///////////////////////////////////////////////////////////////

const (
    ServerServiceName = "Server"

    ServerService_SayHello = 0
)

type ServerServiceClient struct {
    methodCaller pbrpc.MethodCaller
    extraData    []byte
    autoRetry    bool
}

func (self ServerServiceClient) SayHello(context_ context.Context, request *SayHelloRequest) (*SayHelloResponse, error) {
    _ = pbrpc.IncomingMessage(&SayHelloResponse{})
    methodRecord := &methodTableOfServerService[ServerService_SayHello]
    response, e := self.methodCaller.CallMethod(context_, ServerServiceName, methodRecord.Name, methodRecord.Index, self.extraData, request, methodRecord.ResponseType, self.autoRetry)

    if e != nil {
        return nil, e
    }

    return response.(*SayHelloResponse), e
}

func (self ServerServiceClient) WithAutoRetry(autoRetry bool) ServerServiceClient {
    return ServerServiceClient{
        methodCaller: self.methodCaller,
        extraData: self.extraData,
        autoRetry: autoRetry,
    }
}

func (self ServerServiceClient) WithExtraData(extraData []byte) ServerServiceClient {
    return ServerServiceClient{
        methodCaller: self.methodCaller,
        extraData: extraData,
        autoRetry: self.autoRetry,
    }
}

func MakeServerServiceClient(methodCaller pbrpc.MethodCaller) ServerServiceClient {
    return ServerServiceClient{
        methodCaller: methodCaller,
        extraData: nil,
        autoRetry: false,
    }
}

type ServerServiceHandlerBase struct {}

func (ServerServiceHandlerBase) X_GetName() string { return ServerServiceName }
func (ServerServiceHandlerBase) X_GetMethodTable() pbrpc.MethodTable { return methodTableOfServerService }

// `ServerServiceHandler` template:
//
// type ServerServiceHandler struct {
//     ServerServiceHandlerBase
// }
//
// func (ServerServiceHandler) SayHello(context_ context.Context, request *SayHelloRequest) (*SayHelloResponse, error)

var methodTableOfServerService = pbrpc.MethodTable{
    ServerService_SayHello: {
        ServerService_SayHello,
        "SayHello",
        reflect.TypeOf(SayHelloRequest{}),
        reflect.TypeOf(SayHelloResponse{}),

        func(serviceHandler pbrpc.ServiceHandler, context_ context.Context, request interface{}) (pbrpc.OutgoingMessage, error) {
            methodHandler, ok := serviceHandler.(interface { SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error) })

            if !ok {
                return nil, pbrpc.MakeError(pbrpc.ErrorNotImplemented)
            }

            return methodHandler.SayHello(context_, request.(*SayHelloRequest))
        },
    },
}
