/*
 * Code generated by protoc-gen-pbrpc. DO NOT EDIT.
 * source: services.proto
 */

package sample

import (
    "context"
    "reflect"

    pbrpc "github.com/let-z-go/pbrpc"
)

// ClientService ///////////////////////////////////////////////////////////////

const (
    ClientServiceName = "Client"

    ClientService_GetNickname = 0
)

type ClientServiceClient struct {
    MethodCaller pbrpc.MethodCaller
    Context context.Context
}

func (self ClientServiceClient) GetNickname(autoRetry bool) (*GetNicknameResponse, error) {
    methodRecord := &methodTableOfClientService[ClientService_GetNickname]
    response, e := self.MethodCaller.CallMethod(self.Context, ClientServiceName, methodRecord.Name, &pbrpc.Void{}, methodRecord.ResponseType, autoRetry)

    if e != nil {
        return nil, e
    }

    return response.(*GetNicknameResponse), e
}

type ClientServiceHandlerBase struct {}

func (ClientServiceHandlerBase) X_GetName() string { return ClientServiceName }
func (ClientServiceHandlerBase) X_GetMethodTable() pbrpc.MethodTable { return methodTableOfClientService }
func (ClientServiceHandlerBase) X_InterceptMethodCall(*pbrpc.MethodRecord, context.Context, pbrpc.Channel, pbrpc.IncomingMessage) (pbrpc.OutgoingMessage, pbrpc.ErrorCode) { return nil, 0 }

var _ = pbrpc.ServiceHandler(ClientServiceHandlerBase{})

// `ClientServiceHandler` template:
//
// type ClientServiceHandler struct {
//     ClientServiceHandlerBase
// }
//
// func (ClientServiceHandler) X_InterceptMethodCall(methodRecord *pbrpc.MethodRecord, context_ context.Context, channel pbrpc.Channel, request pbrpc.IncomingMessage) (pbrpc.OutgoingMessage, pbrpc.ErrorCode)
// func (ClientServiceHandler) GetNickname(context_ context.Context, channel pbrpc.Channel) (*GetNicknameResponse, error)

var methodTableOfClientService = pbrpc.MethodTable{
    ClientService_GetNickname: {
        ClientService_GetNickname,
        "GetNickname",
        reflect.TypeOf(pbrpc.Void{}),
        reflect.TypeOf(GetNicknameResponse{}),

        func(serviceHandler pbrpc.ServiceHandler, context_ context.Context, channel pbrpc.Channel, _ pbrpc.IncomingMessage) (pbrpc.OutgoingMessage, error) {
            methodHandler, ok := serviceHandler.(interface { GetNickname(context.Context, pbrpc.Channel) (*GetNicknameResponse, error) })

            if !ok {
                return nil, pbrpc.MakeError(pbrpc.ErrorNotImplemented)
            }

            return methodHandler.GetNickname(context_, channel)
        },
    },
}

// ServerService ///////////////////////////////////////////////////////////////

const (
    ServerServiceName = "Server"

    ServerService_SayHello = 0
)

type ServerServiceClient struct {
    MethodCaller pbrpc.MethodCaller
    Context context.Context
}

func (self ServerServiceClient) SayHello(request *SayHelloRequest, autoRetry bool) (*SayHelloResponse, error) {
    methodRecord := &methodTableOfServerService[ServerService_SayHello]
    response, e := self.MethodCaller.CallMethod(self.Context, ServerServiceName, methodRecord.Name, request, methodRecord.ResponseType, autoRetry)

    if e != nil {
        return nil, e
    }

    return response.(*SayHelloResponse), e
}

type ServerServiceHandlerBase struct {}

func (ServerServiceHandlerBase) X_GetName() string { return ServerServiceName }
func (ServerServiceHandlerBase) X_GetMethodTable() pbrpc.MethodTable { return methodTableOfServerService }
func (ServerServiceHandlerBase) X_InterceptMethodCall(*pbrpc.MethodRecord, context.Context, pbrpc.Channel, pbrpc.IncomingMessage) (pbrpc.OutgoingMessage, pbrpc.ErrorCode) { return nil, 0 }

var _ = pbrpc.ServiceHandler(ServerServiceHandlerBase{})

// `ServerServiceHandler` template:
//
// type ServerServiceHandler struct {
//     ServerServiceHandlerBase
// }
//
// func (ServerServiceHandler) X_InterceptMethodCall(methodRecord *pbrpc.MethodRecord, context_ context.Context, channel pbrpc.Channel, request pbrpc.IncomingMessage) (pbrpc.OutgoingMessage, pbrpc.ErrorCode)
// func (ServerServiceHandler) SayHello(context_ context.Context, channel pbrpc.Channel, request *SayHelloRequest) (*SayHelloResponse, error)

var methodTableOfServerService = pbrpc.MethodTable{
    ServerService_SayHello: {
        ServerService_SayHello,
        "SayHello",
        reflect.TypeOf(SayHelloRequest{}),
        reflect.TypeOf(SayHelloResponse{}),

        func(serviceHandler pbrpc.ServiceHandler, context_ context.Context, channel pbrpc.Channel, request pbrpc.IncomingMessage) (pbrpc.OutgoingMessage, error) {
            methodHandler, ok := serviceHandler.(interface { SayHello(context.Context, pbrpc.Channel, *SayHelloRequest) (*SayHelloResponse, error) })

            if !ok {
                return nil, pbrpc.MakeError(pbrpc.ErrorNotImplemented)
            }

            return methodHandler.SayHello(context_, channel, request.(*SayHelloRequest))
        },
    },
}
