// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/let-z-go/gogorpc/internal/protocol/stream.proto

package protocol

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RPCErrorType int32

const (
	RPC_ERROR_NONE                RPCErrorType = 0
	RPC_ERROR_BAD_REQUEST         RPCErrorType = 400
	RPC_ERROR_UNAUTHORIZED        RPCErrorType = 401
	RPC_ERROR_FORBIDDEN           RPCErrorType = 403
	RPC_ERROR_NOT_FOUND           RPCErrorType = 404
	RPC_ERROR_TOO_MANY_REQUESTS   RPCErrorType = 429
	RPC_ERROR_INTERNAL_SERVER     RPCErrorType = 500
	RPC_ERROR_NOT_IMPLEMENTED     RPCErrorType = 501
	RPC_ERROR_BAD_GATEWAY         RPCErrorType = 502
	RPC_ERROR_SERVICE_UNAVAILABLE RPCErrorType = 503
	RPC_ERROR_GATEWAY_TIMEOUT     RPCErrorType = 504
)

var RPCErrorType_name = map[int32]string{
	0:   "RPC_ERROR_NONE",
	400: "RPC_ERROR_BAD_REQUEST",
	401: "RPC_ERROR_UNAUTHORIZED",
	403: "RPC_ERROR_FORBIDDEN",
	404: "RPC_ERROR_NOT_FOUND",
	429: "RPC_ERROR_TOO_MANY_REQUESTS",
	500: "RPC_ERROR_INTERNAL_SERVER",
	501: "RPC_ERROR_NOT_IMPLEMENTED",
	502: "RPC_ERROR_BAD_GATEWAY",
	503: "RPC_ERROR_SERVICE_UNAVAILABLE",
	504: "RPC_ERROR_GATEWAY_TIMEOUT",
}

var RPCErrorType_value = map[string]int32{
	"RPC_ERROR_NONE":                0,
	"RPC_ERROR_BAD_REQUEST":         400,
	"RPC_ERROR_UNAUTHORIZED":        401,
	"RPC_ERROR_FORBIDDEN":           403,
	"RPC_ERROR_NOT_FOUND":           404,
	"RPC_ERROR_TOO_MANY_REQUESTS":   429,
	"RPC_ERROR_INTERNAL_SERVER":     500,
	"RPC_ERROR_NOT_IMPLEMENTED":     501,
	"RPC_ERROR_BAD_GATEWAY":         502,
	"RPC_ERROR_SERVICE_UNAVAILABLE": 503,
	"RPC_ERROR_GATEWAY_TIMEOUT":     504,
}

func (x RPCErrorType) String() string {
	return proto.EnumName(RPCErrorType_name, int32(x))
}

func (RPCErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_215647653449e6ba, []int{0}
}

type HangupCode int32

const (
	HANGUP_ABORTED                    HangupCode = 0
	HANGUP_BAD_INCOMING_PACKET        HangupCode = 1
	HANGUP_TOO_MANY_INCOMING_REQUESTS HangupCode = 2
	HANGUP_OUTGOING_PACKET_TOO_LARGE  HangupCode = 3
	HANGUP_SYSTEM                     HangupCode = 4
)

var HangupCode_name = map[int32]string{
	0: "HANGUP_ABORTED",
	1: "HANGUP_BAD_INCOMING_PACKET",
	2: "HANGUP_TOO_MANY_INCOMING_REQUESTS",
	3: "HANGUP_OUTGOING_PACKET_TOO_LARGE",
	4: "HANGUP_SYSTEM",
}

var HangupCode_value = map[string]int32{
	"HANGUP_ABORTED":                    0,
	"HANGUP_BAD_INCOMING_PACKET":        1,
	"HANGUP_TOO_MANY_INCOMING_REQUESTS": 2,
	"HANGUP_OUTGOING_PACKET_TOO_LARGE":  3,
	"HANGUP_SYSTEM":                     4,
}

func (x HangupCode) String() string {
	return proto.EnumName(HangupCode_name, int32(x))
}

func (HangupCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_215647653449e6ba, []int{1}
}

type StreamHandshakeHeader struct {
	IncomingKeepaliveInterval int32 `protobuf:"varint,1,opt,name=incoming_keepalive_interval,json=incomingKeepaliveInterval,proto3" json:"incoming_keepalive_interval,omitempty"`
	OutgoingKeepaliveInterval int32 `protobuf:"varint,2,opt,name=outgoing_keepalive_interval,json=outgoingKeepaliveInterval,proto3" json:"outgoing_keepalive_interval,omitempty"`
	IncomingConcurrencyLimit  int32 `protobuf:"varint,3,opt,name=incoming_concurrency_limit,json=incomingConcurrencyLimit,proto3" json:"incoming_concurrency_limit,omitempty"`
	OutgoingConcurrencyLimit  int32 `protobuf:"varint,4,opt,name=outgoing_concurrency_limit,json=outgoingConcurrencyLimit,proto3" json:"outgoing_concurrency_limit,omitempty"`
}

func (m *StreamHandshakeHeader) Reset()         { *m = StreamHandshakeHeader{} }
func (m *StreamHandshakeHeader) String() string { return proto.CompactTextString(m) }
func (*StreamHandshakeHeader) ProtoMessage()    {}
func (*StreamHandshakeHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_215647653449e6ba, []int{0}
}
func (m *StreamHandshakeHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamHandshakeHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamHandshakeHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamHandshakeHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamHandshakeHeader.Merge(m, src)
}
func (m *StreamHandshakeHeader) XXX_Size() int {
	return m.Size()
}
func (m *StreamHandshakeHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamHandshakeHeader.DiscardUnknown(m)
}

var xxx_messageInfo_StreamHandshakeHeader proto.InternalMessageInfo

func (m *StreamHandshakeHeader) GetIncomingKeepaliveInterval() int32 {
	if m != nil {
		return m.IncomingKeepaliveInterval
	}
	return 0
}

func (m *StreamHandshakeHeader) GetOutgoingKeepaliveInterval() int32 {
	if m != nil {
		return m.OutgoingKeepaliveInterval
	}
	return 0
}

func (m *StreamHandshakeHeader) GetIncomingConcurrencyLimit() int32 {
	if m != nil {
		return m.IncomingConcurrencyLimit
	}
	return 0
}

func (m *StreamHandshakeHeader) GetOutgoingConcurrencyLimit() int32 {
	if m != nil {
		return m.OutgoingConcurrencyLimit
	}
	return 0
}

type RequestHeader struct {
	SequenceNumber int32             `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	ServiceName    string            `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName     string            `protobuf:"bytes,3,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	ExtraData      map[string][]byte `protobuf:"bytes,4,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Deadline       int64             `protobuf:"varint,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	TraceId        UUID              `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_215647653449e6ba, []int{1}
}
func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return m.Size()
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetSequenceNumber() int32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *RequestHeader) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *RequestHeader) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *RequestHeader) GetExtraData() map[string][]byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *RequestHeader) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *RequestHeader) GetTraceId() UUID {
	if m != nil {
		return m.TraceId
	}
	return UUID{}
}

type ResponseHeader struct {
	SequenceNumber int32             `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	ExtraData      map[string][]byte `protobuf:"bytes,2,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ErrorType      RPCErrorType      `protobuf:"varint,3,opt,name=error_type,json=errorType,proto3,enum=gogorpc.protocol.RPCErrorType" json:"error_type,omitempty"`
	ErrorName      string            `protobuf:"bytes,4,opt,name=error_name,json=errorName,proto3" json:"error_name,omitempty"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_215647653449e6ba, []int{2}
}
func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return m.Size()
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetSequenceNumber() int32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ResponseHeader) GetExtraData() map[string][]byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *ResponseHeader) GetErrorType() RPCErrorType {
	if m != nil {
		return m.ErrorType
	}
	return RPC_ERROR_NONE
}

func (m *ResponseHeader) GetErrorName() string {
	if m != nil {
		return m.ErrorName
	}
	return ""
}

type Hangup struct {
	Code      HangupCode        `protobuf:"varint,1,opt,name=code,proto3,enum=gogorpc.protocol.HangupCode" json:"code,omitempty"`
	ExtraData map[string][]byte `protobuf:"bytes,2,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Hangup) Reset()         { *m = Hangup{} }
func (m *Hangup) String() string { return proto.CompactTextString(m) }
func (*Hangup) ProtoMessage()    {}
func (*Hangup) Descriptor() ([]byte, []int) {
	return fileDescriptor_215647653449e6ba, []int{3}
}
func (m *Hangup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Hangup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Hangup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Hangup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hangup.Merge(m, src)
}
func (m *Hangup) XXX_Size() int {
	return m.Size()
}
func (m *Hangup) XXX_DiscardUnknown() {
	xxx_messageInfo_Hangup.DiscardUnknown(m)
}

var xxx_messageInfo_Hangup proto.InternalMessageInfo

func (m *Hangup) GetCode() HangupCode {
	if m != nil {
		return m.Code
	}
	return HANGUP_ABORTED
}

func (m *Hangup) GetExtraData() map[string][]byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func init() {
	proto.RegisterEnum("gogorpc.protocol.RPCErrorType", RPCErrorType_name, RPCErrorType_value)
	proto.RegisterEnum("gogorpc.protocol.HangupCode", HangupCode_name, HangupCode_value)
	proto.RegisterType((*StreamHandshakeHeader)(nil), "gogorpc.protocol.StreamHandshakeHeader")
	proto.RegisterType((*RequestHeader)(nil), "gogorpc.protocol.RequestHeader")
	proto.RegisterMapType((map[string][]byte)(nil), "gogorpc.protocol.RequestHeader.ExtraDataEntry")
	proto.RegisterType((*ResponseHeader)(nil), "gogorpc.protocol.ResponseHeader")
	proto.RegisterMapType((map[string][]byte)(nil), "gogorpc.protocol.ResponseHeader.ExtraDataEntry")
	proto.RegisterType((*Hangup)(nil), "gogorpc.protocol.Hangup")
	proto.RegisterMapType((map[string][]byte)(nil), "gogorpc.protocol.Hangup.ExtraDataEntry")
}

func init() {
	proto.RegisterFile("github.com/let-z-go/gogorpc/internal/protocol/stream.proto", fileDescriptor_215647653449e6ba)
}

var fileDescriptor_215647653449e6ba = []byte{
	// 887 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xcf, 0x6e, 0xdb, 0x46,
	0x10, 0xc6, 0x45, 0x51, 0x76, 0xe3, 0xb1, 0xa3, 0xb2, 0xdb, 0x26, 0x50, 0xe4, 0x86, 0x51, 0x8c,
	0x16, 0x31, 0x02, 0x58, 0x2a, 0xdc, 0x43, 0x83, 0x20, 0x2d, 0x40, 0x49, 0x6b, 0x89, 0xb0, 0x44,
	0xaa, 0x2b, 0x2a, 0x85, 0x73, 0x21, 0xd6, 0xe4, 0x56, 0x26, 0x2c, 0x91, 0x2a, 0x45, 0x1a, 0x55,
	0x9f, 0x22, 0x45, 0xfa, 0x00, 0xbd, 0xf4, 0xd8, 0x77, 0xe8, 0x31, 0x47, 0xf7, 0xd6, 0x53, 0xd0,
	0xda, 0xaf, 0xd0, 0x7f, 0xc7, 0x82, 0x4b, 0x52, 0xb4, 0x25, 0xbb, 0x80, 0x91, 0x1b, 0x67, 0xbe,
	0xdf, 0x37, 0xb3, 0xfb, 0xad, 0x00, 0xc1, 0xd3, 0xa1, 0x13, 0x1c, 0x85, 0x87, 0x55, 0xcb, 0x1b,
	0xd7, 0x46, 0x2c, 0xd8, 0xf9, 0x6e, 0x67, 0xe8, 0xd5, 0x86, 0xde, 0xd0, 0xf3, 0x27, 0x56, 0xcd,
	0x71, 0x03, 0xe6, 0xbb, 0x74, 0x54, 0x9b, 0xf8, 0x5e, 0xe0, 0x59, 0xde, 0xa8, 0x36, 0x0d, 0x7c,
	0x46, 0xc7, 0x55, 0x5e, 0x23, 0x29, 0xe1, 0xaa, 0xa9, 0x5c, 0xde, 0xb9, 0x30, 0x2d, 0x12, 0x63,
	0xe3, 0x61, 0xf8, 0x35, 0xaf, 0x78, 0xc1, 0xbf, 0x62, 0x47, 0xf9, 0xc9, 0xcd, 0x96, 0x87, 0xa1,
	0x63, 0xc7, 0xce, 0xad, 0x57, 0x79, 0xb8, 0xd3, 0xe7, 0x67, 0x69, 0x53, 0xd7, 0x9e, 0x1e, 0xd1,
	0x63, 0xd6, 0x66, 0xd4, 0x66, 0x3e, 0xfa, 0x02, 0x36, 0x1d, 0xd7, 0xf2, 0xc6, 0x8e, 0x3b, 0x34,
	0x8f, 0x19, 0x9b, 0xd0, 0x91, 0x73, 0xc2, 0x4c, 0x3e, 0xec, 0x84, 0x8e, 0x4a, 0x42, 0x45, 0xd8,
	0x5e, 0x21, 0xf7, 0x52, 0x64, 0x3f, 0x25, 0xd4, 0x04, 0x88, 0xfc, 0x5e, 0x18, 0x0c, 0xbd, 0x6b,
	0xfc, 0xf9, 0xd8, 0x9f, 0x22, 0xcb, 0xfe, 0x67, 0x50, 0x9e, 0xef, 0xb7, 0x3c, 0xd7, 0x0a, 0x7d,
	0x9f, 0xb9, 0xd6, 0xcc, 0x1c, 0x39, 0x63, 0x27, 0x28, 0x89, 0xdc, 0x5e, 0x4a, 0x89, 0x46, 0x06,
	0x74, 0x22, 0x3d, 0x72, 0xcf, 0xb7, 0x2f, 0xbb, 0x0b, 0xb1, 0x3b, 0x25, 0x16, 0xdd, 0x5b, 0x6f,
	0xf2, 0x70, 0x9b, 0xb0, 0x6f, 0x42, 0x36, 0x0d, 0x92, 0x34, 0x1e, 0xc1, 0xbb, 0xd3, 0xa8, 0xe1,
	0x5a, 0xcc, 0x74, 0xc3, 0xf1, 0x21, 0xf3, 0x93, 0x04, 0x8a, 0x69, 0x5b, 0xe3, 0x5d, 0xf4, 0x10,
	0x36, 0xa6, 0xcc, 0x3f, 0x71, 0x22, 0x8e, 0x8e, 0x19, 0xbf, 0xe7, 0x1a, 0x59, 0x4f, 0x7a, 0x1a,
	0x1d, 0x33, 0xf4, 0x00, 0xd6, 0xc7, 0x2c, 0x38, 0xf2, 0xec, 0x98, 0x10, 0x39, 0x01, 0x71, 0x8b,
	0x03, 0x5d, 0x00, 0xf6, 0x6d, 0xe0, 0x53, 0xd3, 0xa6, 0x01, 0x2d, 0x15, 0x2a, 0xe2, 0xf6, 0xfa,
	0x6e, 0xb5, 0xba, 0xf8, 0x23, 0xa9, 0x5e, 0x3a, 0x61, 0x15, 0x47, 0x8e, 0x26, 0x0d, 0x28, 0x76,
	0x03, 0x7f, 0x46, 0xd6, 0x58, 0x5a, 0xa3, 0x32, 0xdc, 0xb2, 0x19, 0xb5, 0x47, 0x8e, 0xcb, 0x4a,
	0x2b, 0x15, 0x61, 0x5b, 0x24, 0xf3, 0x1a, 0x7d, 0x06, 0xb7, 0x02, 0x9f, 0x5a, 0xcc, 0x74, 0xec,
	0xd2, 0x6a, 0x45, 0xd8, 0x5e, 0xdf, 0xbd, 0xbb, 0xbc, 0x68, 0x30, 0x50, 0x9b, 0xf5, 0xc2, 0xeb,
	0x37, 0x0f, 0x72, 0xe4, 0x1d, 0x4e, 0xab, 0x76, 0xf9, 0x19, 0x14, 0x2f, 0x6f, 0x44, 0x12, 0x88,
	0xc7, 0x6c, 0xc6, 0x63, 0x59, 0x23, 0xd1, 0x27, 0xfa, 0x00, 0x56, 0x4e, 0xe8, 0x28, 0x8c, 0x43,
	0xd8, 0x20, 0x71, 0xf1, 0x34, 0xff, 0x44, 0xd8, 0xfa, 0x29, 0x0f, 0x45, 0xc2, 0xa6, 0x13, 0xcf,
	0x9d, 0xb2, 0x9b, 0x26, 0xac, 0x5d, 0x4a, 0x27, 0xcf, 0xd3, 0xa9, 0x5d, 0x95, 0xce, 0xc5, 0xf1,
	0xff, 0x13, 0xcf, 0xe7, 0x00, 0xcc, 0xf7, 0x3d, 0xdf, 0x0c, 0x66, 0x93, 0xf8, 0x35, 0x8a, 0xbb,
	0xf2, 0x15, 0xf3, 0x7a, 0x0d, 0x1c, 0x61, 0xc6, 0x6c, 0xc2, 0xc8, 0x1a, 0x4b, 0x3f, 0xd1, 0xfd,
	0xd4, 0xce, 0x1f, 0xb3, 0xc0, 0x6f, 0x1f, 0xcb, 0xd1, 0x5b, 0xbe, 0x65, 0x4e, 0xbf, 0x08, 0xb0,
	0xda, 0xa6, 0xee, 0x30, 0x9c, 0xa0, 0x4f, 0xa0, 0x60, 0x79, 0x36, 0xe3, 0xbe, 0xe2, 0xee, 0x87,
	0xcb, 0x07, 0x8c, 0xb9, 0x86, 0x67, 0x33, 0xc2, 0x49, 0xb4, 0x77, 0x45, 0x50, 0x8f, 0xae, 0xf3,
	0x5d, 0x1f, 0xd0, 0xdb, 0x5d, 0xe1, 0xf1, 0xaf, 0x79, 0xd8, 0xb8, 0x98, 0x1d, 0x42, 0x50, 0x24,
	0xbd, 0x86, 0x89, 0x09, 0xd1, 0x89, 0xa9, 0xe9, 0x1a, 0x96, 0x72, 0xa8, 0x0c, 0x77, 0xb2, 0x5e,
	0x5d, 0x69, 0x9a, 0x04, 0x7f, 0x39, 0xc0, 0x7d, 0x43, 0x7a, 0x29, 0xa2, 0x4d, 0xb8, 0x9b, 0x69,
	0x03, 0x4d, 0x19, 0x18, 0x6d, 0x9d, 0xa8, 0x2f, 0x70, 0x53, 0xfa, 0x5e, 0x44, 0x25, 0x78, 0x3f,
	0x13, 0xf7, 0x74, 0x52, 0x57, 0x9b, 0x4d, 0xac, 0x49, 0xaf, 0x16, 0x14, 0x4d, 0x37, 0xcc, 0x3d,
	0x7d, 0xa0, 0x35, 0xa5, 0x1f, 0x44, 0x54, 0x81, 0xcd, 0x4c, 0x31, 0x74, 0xdd, 0xec, 0x2a, 0xda,
	0x41, 0xba, 0xb1, 0x2f, 0xfd, 0x2c, 0x22, 0x19, 0xee, 0x65, 0x84, 0xaa, 0x19, 0x98, 0x68, 0x4a,
	0xc7, 0xec, 0x63, 0xf2, 0x1c, 0x13, 0xe9, 0xcf, 0x05, 0x3d, 0x9a, 0xad, 0x76, 0x7b, 0x1d, 0xdc,
	0xc5, 0x9a, 0x81, 0x9b, 0xd2, 0x5f, 0xe2, 0xf2, 0x75, 0x5a, 0x8a, 0x81, 0xbf, 0x52, 0x0e, 0xa4,
	0xbf, 0x45, 0xb4, 0x05, 0xf7, 0x33, 0x2d, 0x1a, 0xa9, 0x36, 0x70, 0x74, 0xad, 0xe7, 0x8a, 0xda,
	0x51, 0xea, 0x1d, 0x2c, 0xfd, 0xb3, 0x30, 0x3f, 0xf1, 0x9a, 0x86, 0xda, 0xc5, 0xfa, 0xc0, 0x90,
	0xfe, 0x15, 0x1f, 0xff, 0x28, 0x00, 0x64, 0xcf, 0x1d, 0x25, 0xda, 0x56, 0xb4, 0xd6, 0xa0, 0x67,
	0x2a, 0x75, 0x9d, 0x44, 0x67, 0xc8, 0x21, 0x19, 0xca, 0x49, 0x2f, 0xda, 0xaf, 0x6a, 0x0d, 0xbd,
	0xab, 0x6a, 0x2d, 0xb3, 0xa7, 0x34, 0xf6, 0xb1, 0x21, 0x09, 0xe8, 0x63, 0x78, 0x98, 0xe8, 0xf3,
	0x04, 0xe6, 0xd0, 0x3c, 0x8a, 0x3c, 0xfa, 0x08, 0x2a, 0x09, 0xa6, 0x0f, 0x8c, 0x96, 0x9e, 0x8d,
	0xe0, 0xb6, 0x8e, 0x42, 0x5a, 0x58, 0x12, 0xd1, 0x7b, 0x70, 0x3b, 0xa1, 0xfa, 0x07, 0x7d, 0x03,
	0x77, 0xa5, 0x42, 0x7d, 0xff, 0xf4, 0x0f, 0x39, 0xf7, 0xfa, 0x4c, 0x16, 0x4e, 0xcf, 0x64, 0xe1,
	0xf7, 0x33, 0x59, 0x78, 0x79, 0x2e, 0xe7, 0x4e, 0xcf, 0xe5, 0xdc, 0x6f, 0xe7, 0x72, 0xee, 0xc5,
	0xce, 0x8d, 0xfe, 0xb0, 0x0e, 0x57, 0xf9, 0xd7, 0xa7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x43,
	0xc9, 0xe1, 0x95, 0x65, 0x07, 0x00, 0x00,
}

func (m *StreamHandshakeHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamHandshakeHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamHandshakeHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OutgoingConcurrencyLimit != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.OutgoingConcurrencyLimit))
		i--
		dAtA[i] = 0x20
	}
	if m.IncomingConcurrencyLimit != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.IncomingConcurrencyLimit))
		i--
		dAtA[i] = 0x18
	}
	if m.OutgoingKeepaliveInterval != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.OutgoingKeepaliveInterval))
		i--
		dAtA[i] = 0x10
	}
	if m.IncomingKeepaliveInterval != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.IncomingKeepaliveInterval))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RequestHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TraceId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStream(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.Deadline != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.Deadline))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ExtraData) > 0 {
		for k := range m.ExtraData {
			v := m.ExtraData[k]
			baseI := i
			if len(v) > 0 {
				i -= len(v)
				copy(dAtA[i:], v)
				i = encodeVarintStream(dAtA, i, uint64(len(v)))
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintStream(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintStream(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.MethodName) > 0 {
		i -= len(m.MethodName)
		copy(dAtA[i:], m.MethodName)
		i = encodeVarintStream(dAtA, i, uint64(len(m.MethodName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ServiceName) > 0 {
		i -= len(m.ServiceName)
		copy(dAtA[i:], m.ServiceName)
		i = encodeVarintStream(dAtA, i, uint64(len(m.ServiceName)))
		i--
		dAtA[i] = 0x12
	}
	if m.SequenceNumber != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.SequenceNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ResponseHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ErrorName) > 0 {
		i -= len(m.ErrorName)
		copy(dAtA[i:], m.ErrorName)
		i = encodeVarintStream(dAtA, i, uint64(len(m.ErrorName)))
		i--
		dAtA[i] = 0x22
	}
	if m.ErrorType != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.ErrorType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ExtraData) > 0 {
		for k := range m.ExtraData {
			v := m.ExtraData[k]
			baseI := i
			if len(v) > 0 {
				i -= len(v)
				copy(dAtA[i:], v)
				i = encodeVarintStream(dAtA, i, uint64(len(v)))
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintStream(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintStream(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.SequenceNumber != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.SequenceNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Hangup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Hangup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Hangup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExtraData) > 0 {
		for k := range m.ExtraData {
			v := m.ExtraData[k]
			baseI := i
			if len(v) > 0 {
				i -= len(v)
				copy(dAtA[i:], v)
				i = encodeVarintStream(dAtA, i, uint64(len(v)))
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintStream(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintStream(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Code != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintStream(dAtA []byte, offset int, v uint64) int {
	offset -= sovStream(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StreamHandshakeHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IncomingKeepaliveInterval != 0 {
		n += 1 + sovStream(uint64(m.IncomingKeepaliveInterval))
	}
	if m.OutgoingKeepaliveInterval != 0 {
		n += 1 + sovStream(uint64(m.OutgoingKeepaliveInterval))
	}
	if m.IncomingConcurrencyLimit != 0 {
		n += 1 + sovStream(uint64(m.IncomingConcurrencyLimit))
	}
	if m.OutgoingConcurrencyLimit != 0 {
		n += 1 + sovStream(uint64(m.OutgoingConcurrencyLimit))
	}
	return n
}

func (m *RequestHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SequenceNumber != 0 {
		n += 1 + sovStream(uint64(m.SequenceNumber))
	}
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovStream(uint64(l))
	}
	l = len(m.MethodName)
	if l > 0 {
		n += 1 + l + sovStream(uint64(l))
	}
	if len(m.ExtraData) > 0 {
		for k, v := range m.ExtraData {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovStream(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovStream(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovStream(uint64(mapEntrySize))
		}
	}
	if m.Deadline != 0 {
		n += 1 + sovStream(uint64(m.Deadline))
	}
	l = m.TraceId.Size()
	n += 1 + l + sovStream(uint64(l))
	return n
}

func (m *ResponseHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SequenceNumber != 0 {
		n += 1 + sovStream(uint64(m.SequenceNumber))
	}
	if len(m.ExtraData) > 0 {
		for k, v := range m.ExtraData {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovStream(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovStream(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovStream(uint64(mapEntrySize))
		}
	}
	if m.ErrorType != 0 {
		n += 1 + sovStream(uint64(m.ErrorType))
	}
	l = len(m.ErrorName)
	if l > 0 {
		n += 1 + l + sovStream(uint64(l))
	}
	return n
}

func (m *Hangup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovStream(uint64(m.Code))
	}
	if len(m.ExtraData) > 0 {
		for k, v := range m.ExtraData {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovStream(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovStream(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovStream(uint64(mapEntrySize))
		}
	}
	return n
}

func sovStream(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStream(x uint64) (n int) {
	return sovStream(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StreamHandshakeHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamHandshakeHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamHandshakeHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncomingKeepaliveInterval", wireType)
			}
			m.IncomingKeepaliveInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IncomingKeepaliveInterval |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutgoingKeepaliveInterval", wireType)
			}
			m.OutgoingKeepaliveInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutgoingKeepaliveInterval |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncomingConcurrencyLimit", wireType)
			}
			m.IncomingConcurrencyLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IncomingConcurrencyLimit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutgoingConcurrencyLimit", wireType)
			}
			m.OutgoingConcurrencyLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutgoingConcurrencyLimit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceNumber", wireType)
			}
			m.SequenceNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SequenceNumber |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MethodName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MethodName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExtraData == nil {
				m.ExtraData = make(map[string][]byte)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowStream
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthStream
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthStream
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthStream
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthStream
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipStream(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthStream
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ExtraData[mapkey] = mapvalue
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			m.Deadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TraceId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceNumber", wireType)
			}
			m.SequenceNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SequenceNumber |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExtraData == nil {
				m.ExtraData = make(map[string][]byte)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowStream
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthStream
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthStream
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthStream
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthStream
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipStream(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthStream
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ExtraData[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorType", wireType)
			}
			m.ErrorType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrorType |= RPCErrorType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Hangup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Hangup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Hangup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= HangupCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExtraData == nil {
				m.ExtraData = make(map[string][]byte)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowStream
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthStream
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthStream
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthStream
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthStream
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipStream(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthStream
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ExtraData[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStream(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStream
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStream
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthStream
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowStream
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipStream(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthStream
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthStream = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStream   = fmt.Errorf("proto: integer overflow")
)
