// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protocol/stream.proto

package protocol

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RPCErrorCode int32

const (
	RPC_ERROR_NONE                RPCErrorCode = 0
	RPC_ERROR_BAD_REQUEST         RPCErrorCode = 400
	RPC_ERROR_UNAUTHORIZED        RPCErrorCode = 401
	RPC_ERROR_FORBIDDEN           RPCErrorCode = 403
	RPC_ERROR_NOT_FOUND           RPCErrorCode = 404
	RPC_ERROR_TOO_MANY_REQUESTS   RPCErrorCode = 429
	RPC_ERROR_INTERNAL_SERVER     RPCErrorCode = 500
	RPC_ERROR_NOT_IMPLEMENTED     RPCErrorCode = 501
	RPC_ERROR_BAD_GATEWAY         RPCErrorCode = 502
	RPC_ERROR_SERVICE_UNAVAILABLE RPCErrorCode = 503
	RPC_ERROR_GATEWAY_TIMEOUT     RPCErrorCode = 504
)

var RPCErrorCode_name = map[int32]string{
	0:   "RPC_ERROR_NONE",
	400: "RPC_ERROR_BAD_REQUEST",
	401: "RPC_ERROR_UNAUTHORIZED",
	403: "RPC_ERROR_FORBIDDEN",
	404: "RPC_ERROR_NOT_FOUND",
	429: "RPC_ERROR_TOO_MANY_REQUESTS",
	500: "RPC_ERROR_INTERNAL_SERVER",
	501: "RPC_ERROR_NOT_IMPLEMENTED",
	502: "RPC_ERROR_BAD_GATEWAY",
	503: "RPC_ERROR_SERVICE_UNAVAILABLE",
	504: "RPC_ERROR_GATEWAY_TIMEOUT",
}

var RPCErrorCode_value = map[string]int32{
	"RPC_ERROR_NONE":                0,
	"RPC_ERROR_BAD_REQUEST":         400,
	"RPC_ERROR_UNAUTHORIZED":        401,
	"RPC_ERROR_FORBIDDEN":           403,
	"RPC_ERROR_NOT_FOUND":           404,
	"RPC_ERROR_TOO_MANY_REQUESTS":   429,
	"RPC_ERROR_INTERNAL_SERVER":     500,
	"RPC_ERROR_NOT_IMPLEMENTED":     501,
	"RPC_ERROR_BAD_GATEWAY":         502,
	"RPC_ERROR_SERVICE_UNAVAILABLE": 503,
	"RPC_ERROR_GATEWAY_TIMEOUT":     504,
}

func (x RPCErrorCode) String() string {
	return proto.EnumName(RPCErrorCode_name, int32(x))
}

func (RPCErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df773e1ecf94133c, []int{0}
}

type ErrorCode int32

const (
	ERROR_ABORTED                    ErrorCode = 0
	ERROR_BAD_INCOMING_PACKET        ErrorCode = 1
	ERROR_TOO_MANY_INCOMING_REQUESTS ErrorCode = 2
	ERROR_OUTGOING_PACKET_TOO_LARGE  ErrorCode = 3
	ERROR_SYSTEM                     ErrorCode = 4
)

var ErrorCode_name = map[int32]string{
	0: "ERROR_ABORTED",
	1: "ERROR_BAD_INCOMING_PACKET",
	2: "ERROR_TOO_MANY_INCOMING_REQUESTS",
	3: "ERROR_OUTGOING_PACKET_TOO_LARGE",
	4: "ERROR_SYSTEM",
}

var ErrorCode_value = map[string]int32{
	"ERROR_ABORTED":                    0,
	"ERROR_BAD_INCOMING_PACKET":        1,
	"ERROR_TOO_MANY_INCOMING_REQUESTS": 2,
	"ERROR_OUTGOING_PACKET_TOO_LARGE":  3,
	"ERROR_SYSTEM":                     4,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df773e1ecf94133c, []int{1}
}

type StreamHandshakeHeader struct {
	IncomingKeepaliveInterval int32 `protobuf:"varint,1,opt,name=incoming_keepalive_interval,json=incomingKeepaliveInterval,proto3" json:"incoming_keepalive_interval,omitempty"`
	OutgoingKeepaliveInterval int32 `protobuf:"varint,2,opt,name=outgoing_keepalive_interval,json=outgoingKeepaliveInterval,proto3" json:"outgoing_keepalive_interval,omitempty"`
	LocalConcurrencyLimit     int32 `protobuf:"varint,3,opt,name=local_concurrency_limit,json=localConcurrencyLimit,proto3" json:"local_concurrency_limit,omitempty"`
	RemoteConcurrencyLimit    int32 `protobuf:"varint,4,opt,name=remote_concurrency_limit,json=remoteConcurrencyLimit,proto3" json:"remote_concurrency_limit,omitempty"`
}

func (m *StreamHandshakeHeader) Reset()         { *m = StreamHandshakeHeader{} }
func (m *StreamHandshakeHeader) String() string { return proto.CompactTextString(m) }
func (*StreamHandshakeHeader) ProtoMessage()    {}
func (*StreamHandshakeHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_df773e1ecf94133c, []int{0}
}
func (m *StreamHandshakeHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamHandshakeHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamHandshakeHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamHandshakeHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamHandshakeHeader.Merge(m, src)
}
func (m *StreamHandshakeHeader) XXX_Size() int {
	return m.Size()
}
func (m *StreamHandshakeHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamHandshakeHeader.DiscardUnknown(m)
}

var xxx_messageInfo_StreamHandshakeHeader proto.InternalMessageInfo

func (m *StreamHandshakeHeader) GetIncomingKeepaliveInterval() int32 {
	if m != nil {
		return m.IncomingKeepaliveInterval
	}
	return 0
}

func (m *StreamHandshakeHeader) GetOutgoingKeepaliveInterval() int32 {
	if m != nil {
		return m.OutgoingKeepaliveInterval
	}
	return 0
}

func (m *StreamHandshakeHeader) GetLocalConcurrencyLimit() int32 {
	if m != nil {
		return m.LocalConcurrencyLimit
	}
	return 0
}

func (m *StreamHandshakeHeader) GetRemoteConcurrencyLimit() int32 {
	if m != nil {
		return m.RemoteConcurrencyLimit
	}
	return 0
}

type RequestHeader struct {
	SequenceNumber int32             `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	TraceId        UUID              `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id"`
	ServiceName    string            `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName     string            `protobuf:"bytes,4,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	ExtraData      map[string][]byte `protobuf:"bytes,5,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Deadline       int64             `protobuf:"varint,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_df773e1ecf94133c, []int{1}
}
func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return m.Size()
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetSequenceNumber() int32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *RequestHeader) GetTraceId() UUID {
	if m != nil {
		return m.TraceId
	}
	return UUID{}
}

func (m *RequestHeader) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *RequestHeader) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *RequestHeader) GetExtraData() map[string][]byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *RequestHeader) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

type ResponseHeader struct {
	SequenceNumber int32             `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	ExtraData      map[string][]byte `protobuf:"bytes,2,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ErrorCode      RPCErrorCode      `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=pbrpc.protocol.RPCErrorCode" json:"error_code,omitempty"`
	ReasonCode     string            `protobuf:"bytes,4,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_df773e1ecf94133c, []int{2}
}
func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return m.Size()
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetSequenceNumber() int32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ResponseHeader) GetExtraData() map[string][]byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *ResponseHeader) GetErrorCode() RPCErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return RPC_ERROR_NONE
}

func (m *ResponseHeader) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

type Hangup struct {
	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=pbrpc.protocol.ErrorCode" json:"error_code,omitempty"`
}

func (m *Hangup) Reset()         { *m = Hangup{} }
func (m *Hangup) String() string { return proto.CompactTextString(m) }
func (*Hangup) ProtoMessage()    {}
func (*Hangup) Descriptor() ([]byte, []int) {
	return fileDescriptor_df773e1ecf94133c, []int{3}
}
func (m *Hangup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Hangup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Hangup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Hangup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hangup.Merge(m, src)
}
func (m *Hangup) XXX_Size() int {
	return m.Size()
}
func (m *Hangup) XXX_DiscardUnknown() {
	xxx_messageInfo_Hangup.DiscardUnknown(m)
}

var xxx_messageInfo_Hangup proto.InternalMessageInfo

func (m *Hangup) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ERROR_ABORTED
}

func init() {
	proto.RegisterEnum("pbrpc.protocol.RPCErrorCode", RPCErrorCode_name, RPCErrorCode_value)
	proto.RegisterEnum("pbrpc.protocol.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*StreamHandshakeHeader)(nil), "pbrpc.protocol.StreamHandshakeHeader")
	proto.RegisterType((*RequestHeader)(nil), "pbrpc.protocol.RequestHeader")
	proto.RegisterMapType((map[string][]byte)(nil), "pbrpc.protocol.RequestHeader.ExtraDataEntry")
	proto.RegisterType((*ResponseHeader)(nil), "pbrpc.protocol.ResponseHeader")
	proto.RegisterMapType((map[string][]byte)(nil), "pbrpc.protocol.ResponseHeader.ExtraDataEntry")
	proto.RegisterType((*Hangup)(nil), "pbrpc.protocol.Hangup")
}

func init() { proto.RegisterFile("protocol/stream.proto", fileDescriptor_df773e1ecf94133c) }

var fileDescriptor_df773e1ecf94133c = []byte{
	// 862 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x8f, 0xe3, 0xb6, 0x6c, 0x5e, 0xbb, 0xc1, 0x0c, 0xdb, 0x25, 0x4d, 0xd9, 0x34, 0x14, 0x24,
	0xaa, 0x85, 0x26, 0x52, 0x11, 0xab, 0x0a, 0x10, 0x92, 0x93, 0xcc, 0xb6, 0x56, 0x13, 0xbb, 0x4c,
	0x9c, 0x45, 0xdd, 0x8b, 0x35, 0xb1, 0x87, 0xd4, 0xaa, 0xe3, 0x09, 0x13, 0xbb, 0xa2, 0x7c, 0x03,
	0x6e, 0x8b, 0xe0, 0xc4, 0x95, 0x33, 0xdf, 0x63, 0x8f, 0xe5, 0x86, 0x38, 0x20, 0x68, 0xbf, 0x02,
	0xff, 0x8e, 0xc8, 0xe3, 0xa4, 0x6e, 0xd2, 0x05, 0xa9, 0xe2, 0x36, 0xef, 0xfd, 0xfe, 0xbc, 0xf7,
	0x7b, 0x3e, 0x18, 0x56, 0x47, 0x82, 0x47, 0xdc, 0xe5, 0x41, 0x7d, 0x1c, 0x09, 0x46, 0x87, 0x35,
	0x59, 0xa3, 0xe2, 0xa8, 0x2f, 0x46, 0x6e, 0x6d, 0x0a, 0x96, 0xb7, 0x07, 0x7e, 0x74, 0x1c, 0xf7,
	0x6b, 0x2e, 0x1f, 0xd6, 0x07, 0x7c, 0xc0, 0xeb, 0x12, 0xe9, 0xc7, 0x9f, 0xc9, 0x4a, 0x16, 0xf2,
	0x95, 0x2a, 0xca, 0x8f, 0xae, 0xd1, 0x03, 0x16, 0x6d, 0x7f, 0xb9, 0x9d, 0x48, 0x12, 0xcb, 0xba,
	0x1f, 0x46, 0x4c, 0x84, 0x34, 0xa8, 0x5f, 0x0d, 0x8e, 0x63, 0xdf, 0x4b, 0x75, 0x9b, 0x5f, 0xe5,
	0x61, 0xb5, 0x2b, 0xf7, 0xd8, 0xa7, 0xa1, 0x37, 0x3e, 0xa6, 0x27, 0x6c, 0x9f, 0x51, 0x8f, 0x09,
	0xf4, 0x31, 0xac, 0xfb, 0xa1, 0xcb, 0x87, 0x7e, 0x38, 0x70, 0x4e, 0x18, 0x1b, 0xd1, 0xc0, 0x3f,
	0x65, 0x8e, 0x34, 0x3b, 0xa5, 0x41, 0x49, 0xa9, 0x2a, 0x5b, 0x8b, 0x64, 0x6d, 0x4a, 0x39, 0x98,
	0x32, 0x8c, 0x09, 0x21, 0xd1, 0xf3, 0x38, 0x1a, 0xf0, 0x7f, 0xd1, 0xe7, 0x53, 0xfd, 0x94, 0x72,
	0x53, 0xff, 0x08, 0x5e, 0x0b, 0xb8, 0x4b, 0x03, 0xc7, 0xe5, 0xa1, 0x1b, 0x0b, 0xc1, 0x42, 0xf7,
	0xcc, 0x09, 0xfc, 0xa1, 0x1f, 0x95, 0x54, 0xa9, 0x5d, 0x95, 0x70, 0x33, 0x43, 0xdb, 0x09, 0x88,
	0x76, 0xa1, 0x24, 0xd8, 0x90, 0x47, 0xec, 0x05, 0xc2, 0x05, 0x29, 0xbc, 0x9f, 0xe2, 0xf3, 0xca,
	0xcd, 0x9f, 0xf3, 0x70, 0x97, 0xb0, 0xcf, 0x63, 0x36, 0x8e, 0x26, 0x37, 0x78, 0x1b, 0x5e, 0x1e,
	0x27, 0x8d, 0xd0, 0x65, 0x4e, 0x18, 0x0f, 0xfb, 0x4c, 0x4c, 0x72, 0x17, 0xa7, 0x6d, 0x53, 0x76,
	0xd1, 0xfb, 0x70, 0x27, 0x12, 0xd4, 0x65, 0x8e, 0xef, 0xc9, 0x64, 0xcb, 0x3b, 0xf7, 0x6a, 0xb3,
	0x1f, 0xb4, 0xd6, 0xeb, 0x19, 0xad, 0xc6, 0xc2, 0xf3, 0x5f, 0x36, 0x72, 0xe4, 0x25, 0xc9, 0x35,
	0x3c, 0xf4, 0x06, 0xac, 0x8c, 0x99, 0x38, 0xf5, 0x13, 0x7b, 0x3a, 0x64, 0x32, 0x58, 0x81, 0x2c,
	0x4f, 0x7a, 0x26, 0x1d, 0x32, 0xb4, 0x01, 0xcb, 0x43, 0x16, 0x1d, 0x73, 0x2f, 0x65, 0x2c, 0x48,
	0x06, 0xa4, 0x2d, 0x49, 0x38, 0x00, 0x60, 0x5f, 0x44, 0x82, 0x3a, 0x1e, 0x8d, 0x68, 0x69, 0xb1,
	0xaa, 0x6e, 0x2d, 0xef, 0xbc, 0x3b, 0x3f, 0x7c, 0x26, 0x56, 0x0d, 0x27, 0xfc, 0x16, 0x8d, 0x28,
	0x0e, 0x23, 0x71, 0x46, 0x0a, 0x6c, 0x5a, 0xa3, 0x32, 0xdc, 0xf1, 0x18, 0xf5, 0x02, 0x3f, 0x64,
	0xa5, 0xa5, 0xaa, 0xb2, 0xa5, 0x92, 0xab, 0xba, 0xfc, 0x11, 0x14, 0x67, 0x85, 0x48, 0x03, 0xf5,
	0x84, 0x9d, 0xc9, 0x93, 0x14, 0x48, 0xf2, 0x44, 0xf7, 0x60, 0xf1, 0x94, 0x06, 0x31, 0x93, 0x47,
	0x58, 0x21, 0x69, 0xf1, 0x41, 0x7e, 0x57, 0xd9, 0xfc, 0x3e, 0x0f, 0x45, 0xc2, 0xc6, 0x23, 0x1e,
	0x8e, 0xd9, 0x6d, 0xaf, 0xdb, 0x9e, 0x89, 0x98, 0x97, 0x11, 0xb7, 0x6f, 0x46, 0xbc, 0x6e, 0xfe,
	0x1f, 0x19, 0x3f, 0x04, 0x60, 0x42, 0x70, 0xe1, 0xb8, 0xdc, 0x4b, 0x4f, 0x5e, 0xdc, 0x79, 0xfd,
	0x86, 0xdb, 0x61, 0x13, 0x27, 0xa4, 0x26, 0xf7, 0x18, 0x29, 0xb0, 0xe9, 0x33, 0xf9, 0x1c, 0x82,
	0xd1, 0x31, 0x0f, 0x53, 0xf5, 0xe4, 0x73, 0xa4, 0xad, 0x84, 0xf0, 0x3f, 0xaf, 0xd4, 0x80, 0xa5,
	0x7d, 0x1a, 0x0e, 0xe2, 0x11, 0xda, 0x9d, 0xd9, 0x52, 0x91, 0x5b, 0xae, 0xcd, 0x6f, 0xf9, 0xa2,
	0x15, 0x1f, 0xfe, 0x98, 0x87, 0x95, 0xeb, 0xeb, 0x23, 0x04, 0x45, 0x72, 0xd8, 0x74, 0x30, 0x21,
	0x16, 0x71, 0x4c, 0xcb, 0xc4, 0x5a, 0x0e, 0x95, 0x61, 0x35, 0xeb, 0x35, 0xf4, 0x96, 0x43, 0xf0,
	0x27, 0x3d, 0xdc, 0xb5, 0xb5, 0x67, 0x2a, 0x5a, 0x87, 0xfb, 0x19, 0xd6, 0x33, 0xf5, 0x9e, 0xbd,
	0x6f, 0x11, 0xe3, 0x29, 0x6e, 0x69, 0x5f, 0xab, 0xa8, 0x04, 0xaf, 0x66, 0xe0, 0x63, 0x8b, 0x34,
	0x8c, 0x56, 0x0b, 0x9b, 0xda, 0x37, 0x73, 0x88, 0x69, 0xd9, 0xce, 0x63, 0xab, 0x67, 0xb6, 0xb4,
	0x6f, 0x55, 0x54, 0x85, 0xf5, 0x0c, 0xb1, 0x2d, 0xcb, 0xe9, 0xe8, 0xe6, 0xd1, 0x74, 0x62, 0x57,
	0xfb, 0x41, 0x45, 0x15, 0x58, 0xcb, 0x18, 0x86, 0x69, 0x63, 0x62, 0xea, 0x6d, 0xa7, 0x8b, 0xc9,
	0x13, 0x4c, 0xb4, 0xdf, 0xe7, 0xf0, 0xc4, 0xdb, 0xe8, 0x1c, 0xb6, 0x71, 0x07, 0x9b, 0x36, 0x6e,
	0x69, 0x7f, 0xa8, 0x37, 0xe3, 0xec, 0xe9, 0x36, 0xfe, 0x54, 0x3f, 0xd2, 0xfe, 0x54, 0xd1, 0x26,
	0x3c, 0xc8, 0xb0, 0xc4, 0xd2, 0x68, 0xe2, 0x24, 0xd6, 0x13, 0xdd, 0x68, 0xeb, 0x8d, 0x36, 0xd6,
	0xfe, 0x9a, 0xf3, 0x9f, 0x68, 0x1d, 0xdb, 0xe8, 0x60, 0xab, 0x67, 0x6b, 0x7f, 0xab, 0x0f, 0xbf,
	0x53, 0xa0, 0x90, 0x1d, 0xf4, 0x15, 0xb8, 0x9b, 0x32, 0xf5, 0x86, 0x45, 0x92, 0x0d, 0x72, 0xe8,
	0x01, 0xac, 0x65, 0xc3, 0x0d, 0xb3, 0x69, 0x75, 0x0c, 0x73, 0xcf, 0x39, 0xd4, 0x9b, 0x07, 0xd8,
	0xd6, 0x14, 0xf4, 0x16, 0x54, 0xe7, 0xd2, 0x5f, 0x71, 0xae, 0xce, 0x90, 0x47, 0x6f, 0xc2, 0x46,
	0xca, 0xb2, 0x7a, 0xf6, 0x9e, 0x95, 0x19, 0x48, 0x55, 0x5b, 0x27, 0x7b, 0x58, 0x53, 0x91, 0x06,
	0x2b, 0x93, 0x28, 0x47, 0x5d, 0x1b, 0x77, 0xb4, 0x85, 0x86, 0x71, 0xfe, 0x5b, 0x25, 0xf7, 0xfc,
	0xa2, 0xa2, 0x9c, 0x5f, 0x54, 0x94, 0x5f, 0x2f, 0x2a, 0xca, 0xb3, 0xcb, 0x4a, 0xee, 0xfc, 0xb2,
	0x92, 0xfb, 0xe9, 0xb2, 0x92, 0x7b, 0xfa, 0xce, 0x2d, 0xfe, 0x0c, 0xfd, 0x25, 0xf9, 0x7a, 0xef,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xa7, 0xcb, 0x34, 0xa5, 0x06, 0x00, 0x00,
}

func (m *StreamHandshakeHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamHandshakeHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.IncomingKeepaliveInterval != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintStream(dAtA, i, uint64(m.IncomingKeepaliveInterval))
	}
	if m.OutgoingKeepaliveInterval != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintStream(dAtA, i, uint64(m.OutgoingKeepaliveInterval))
	}
	if m.LocalConcurrencyLimit != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintStream(dAtA, i, uint64(m.LocalConcurrencyLimit))
	}
	if m.RemoteConcurrencyLimit != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintStream(dAtA, i, uint64(m.RemoteConcurrencyLimit))
	}
	return i, nil
}

func (m *RequestHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SequenceNumber != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintStream(dAtA, i, uint64(m.SequenceNumber))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintStream(dAtA, i, uint64(m.TraceId.Size()))
	n1, err1 := m.TraceId.MarshalTo(dAtA[i:])
	if err1 != nil {
		return 0, err1
	}
	i += n1
	if len(m.ServiceName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintStream(dAtA, i, uint64(len(m.ServiceName)))
		i += copy(dAtA[i:], m.ServiceName)
	}
	if len(m.MethodName) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintStream(dAtA, i, uint64(len(m.MethodName)))
		i += copy(dAtA[i:], m.MethodName)
	}
	if len(m.ExtraData) > 0 {
		for k, _ := range m.ExtraData {
			dAtA[i] = 0x2a
			i++
			v := m.ExtraData[k]
			byteSize := 0
			if len(v) > 0 {
				byteSize = 1 + len(v) + sovStream(uint64(len(v)))
			}
			mapSize := 1 + len(k) + sovStream(uint64(len(k))) + byteSize
			i = encodeVarintStream(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintStream(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if len(v) > 0 {
				dAtA[i] = 0x12
				i++
				i = encodeVarintStream(dAtA, i, uint64(len(v)))
				i += copy(dAtA[i:], v)
			}
		}
	}
	if m.Deadline != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintStream(dAtA, i, uint64(m.Deadline))
	}
	return i, nil
}

func (m *ResponseHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SequenceNumber != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintStream(dAtA, i, uint64(m.SequenceNumber))
	}
	if len(m.ExtraData) > 0 {
		for k, _ := range m.ExtraData {
			dAtA[i] = 0x12
			i++
			v := m.ExtraData[k]
			byteSize := 0
			if len(v) > 0 {
				byteSize = 1 + len(v) + sovStream(uint64(len(v)))
			}
			mapSize := 1 + len(k) + sovStream(uint64(len(k))) + byteSize
			i = encodeVarintStream(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintStream(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if len(v) > 0 {
				dAtA[i] = 0x12
				i++
				i = encodeVarintStream(dAtA, i, uint64(len(v)))
				i += copy(dAtA[i:], v)
			}
		}
	}
	if m.ErrorCode != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintStream(dAtA, i, uint64(m.ErrorCode))
	}
	if len(m.ReasonCode) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintStream(dAtA, i, uint64(len(m.ReasonCode)))
		i += copy(dAtA[i:], m.ReasonCode)
	}
	return i, nil
}

func (m *Hangup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Hangup) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ErrorCode != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintStream(dAtA, i, uint64(m.ErrorCode))
	}
	return i, nil
}

func encodeVarintStream(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *StreamHandshakeHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IncomingKeepaliveInterval != 0 {
		n += 1 + sovStream(uint64(m.IncomingKeepaliveInterval))
	}
	if m.OutgoingKeepaliveInterval != 0 {
		n += 1 + sovStream(uint64(m.OutgoingKeepaliveInterval))
	}
	if m.LocalConcurrencyLimit != 0 {
		n += 1 + sovStream(uint64(m.LocalConcurrencyLimit))
	}
	if m.RemoteConcurrencyLimit != 0 {
		n += 1 + sovStream(uint64(m.RemoteConcurrencyLimit))
	}
	return n
}

func (m *RequestHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SequenceNumber != 0 {
		n += 1 + sovStream(uint64(m.SequenceNumber))
	}
	l = m.TraceId.Size()
	n += 1 + l + sovStream(uint64(l))
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovStream(uint64(l))
	}
	l = len(m.MethodName)
	if l > 0 {
		n += 1 + l + sovStream(uint64(l))
	}
	if len(m.ExtraData) > 0 {
		for k, v := range m.ExtraData {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovStream(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovStream(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovStream(uint64(mapEntrySize))
		}
	}
	if m.Deadline != 0 {
		n += 1 + sovStream(uint64(m.Deadline))
	}
	return n
}

func (m *ResponseHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SequenceNumber != 0 {
		n += 1 + sovStream(uint64(m.SequenceNumber))
	}
	if len(m.ExtraData) > 0 {
		for k, v := range m.ExtraData {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovStream(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovStream(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovStream(uint64(mapEntrySize))
		}
	}
	if m.ErrorCode != 0 {
		n += 1 + sovStream(uint64(m.ErrorCode))
	}
	l = len(m.ReasonCode)
	if l > 0 {
		n += 1 + l + sovStream(uint64(l))
	}
	return n
}

func (m *Hangup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ErrorCode != 0 {
		n += 1 + sovStream(uint64(m.ErrorCode))
	}
	return n
}

func sovStream(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStream(x uint64) (n int) {
	return sovStream(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StreamHandshakeHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamHandshakeHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamHandshakeHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncomingKeepaliveInterval", wireType)
			}
			m.IncomingKeepaliveInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IncomingKeepaliveInterval |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutgoingKeepaliveInterval", wireType)
			}
			m.OutgoingKeepaliveInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutgoingKeepaliveInterval |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalConcurrencyLimit", wireType)
			}
			m.LocalConcurrencyLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LocalConcurrencyLimit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteConcurrencyLimit", wireType)
			}
			m.RemoteConcurrencyLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemoteConcurrencyLimit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceNumber", wireType)
			}
			m.SequenceNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SequenceNumber |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TraceId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MethodName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MethodName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExtraData == nil {
				m.ExtraData = make(map[string][]byte)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowStream
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthStream
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthStream
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthStream
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthStream
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipStream(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthStream
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ExtraData[mapkey] = mapvalue
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			m.Deadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SequenceNumber", wireType)
			}
			m.SequenceNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SequenceNumber |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExtraData == nil {
				m.ExtraData = make(map[string][]byte)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowStream
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthStream
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthStream
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStream
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthStream
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthStream
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipStream(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthStream
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ExtraData[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			m.ErrorCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrorCode |= RPCErrorCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReasonCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReasonCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Hangup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Hangup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Hangup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			m.ErrorCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrorCode |= ErrorCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStream(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStream
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStream
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthStream
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowStream
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipStream(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthStream
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthStream = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStream   = fmt.Errorf("proto: integer overflow")
)
