/*
 * Generated by protoc-gen-gogorpc. DO NOT EDIT!
 */

package protocol

import (
	context "context"
	channel "github.com/let-z-go/gogorpc/channel"
)

var (
	RPCErrForbiddenName = channel.NewRPCError(channel.RPCErrorType(403), "examples.helloworld.ForbiddenName")
)

const Greeter = "examples.helloworld.Greeter"

const (
	Greeter_SayHello  = "SayHello"
	Greeter_SayHello2 = "SayHello2"
	Greeter_SayHello3 = "SayHello3"
)

type GreeterHandler interface {
	SayHello(ctx context.Context, request *SayHelloReq) (response *SayHelloResp, err error)
	SayHello2(ctx context.Context, request *SayHelloReq) (err error)
	SayHello3(ctx context.Context) (response *SayHelloResp, err error)
}

func RegisterGreeterHandler(serviceHandler GreeterHandler) func(*channel.Options) {
	return func(options *channel.Options) {
		options.
			BuildMethod(Greeter, Greeter_SayHello).
			SetRequestFactory(func() channel.Message {
				return new(SayHelloReq)
			}).
			SetIncomingRPCHandler(func(rpc *channel.RPC) {
				response, err := serviceHandler.SayHello(rpc.Ctx, rpc.Request.(*SayHelloReq))

				if response == nil {
					rpc.Response = channel.NullMessage
				} else {
					rpc.Response = response
				}

				rpc.Err = err
			}).
			End().
			BuildMethod(Greeter, Greeter_SayHello2).
			SetRequestFactory(func() channel.Message {
				return new(SayHelloReq)
			}).
			SetIncomingRPCHandler(func(rpc *channel.RPC) {
				rpc.Response = channel.NullMessage
				rpc.Err = serviceHandler.SayHello2(rpc.Ctx, rpc.Request.(*SayHelloReq))
			}).
			End().
			BuildMethod(Greeter, Greeter_SayHello3).
			SetIncomingRPCHandler(func(rpc *channel.RPC) {
				response, err := serviceHandler.SayHello3(rpc.Ctx)

				if response == nil {
					rpc.Response = channel.NullMessage
				} else {
					rpc.Response = response
				}

				rpc.Err = err
			}).
			End()
	}
}

type GreeterStub struct {
	rpcPreparer      channel.RPCPreparer
	requestExtraData channel.ExtraData
}

func (self *GreeterStub) Init(rpcPreparer channel.RPCPreparer) *GreeterStub {
	self.rpcPreparer = rpcPreparer
	return self
}

func (self *GreeterStub) WithRequestExtraData(extraData channel.ExtraData) *GreeterStub {
	self.requestExtraData = extraData
	return self
}

func (self GreeterStub) SayHello(ctx context.Context, request *SayHelloReq) (*SayHelloResp, error) {
	rpc := self.MakeSayHello(ctx, request).Do()
	response, err := rpc.Result()
	rpc.Close()
	return response, err
}

func (self GreeterStub) MakeSayHello(ctx context.Context, request *SayHelloReq) GreeterStub_SayHello {
	rpc := channel.GetPooledRPC()

	*rpc = channel.RPC{
		Ctx:              ctx,
		ServiceID:        Greeter,
		MethodName:       Greeter_SayHello,
		RequestExtraData: self.requestExtraData.Ref(true),
		Request:          request,
	}

	self.rpcPreparer.PrepareRPC(rpc, func() channel.Message {
		return new(SayHelloResp)
	})

	return GreeterStub_SayHello{rpc}
}

func (self GreeterStub) SayHello2(ctx context.Context, request *SayHelloReq) error {
	rpc := self.MakeSayHello2(ctx, request).Do()
	err := rpc.Result()
	rpc.Close()
	return err
}

func (self GreeterStub) MakeSayHello2(ctx context.Context, request *SayHelloReq) GreeterStub_SayHello2 {
	rpc := channel.GetPooledRPC()

	*rpc = channel.RPC{
		Ctx:              ctx,
		ServiceID:        Greeter,
		MethodName:       Greeter_SayHello2,
		RequestExtraData: self.requestExtraData.Ref(true),
		Request:          request,
	}

	self.rpcPreparer.PrepareRPC(rpc, channel.GetNullMessage)
	return GreeterStub_SayHello2{rpc}
}

func (self GreeterStub) SayHello3(ctx context.Context) (*SayHelloResp, error) {
	rpc := self.MakeSayHello3(ctx).Do()
	response, err := rpc.Result()
	rpc.Close()
	return response, err
}

func (self GreeterStub) MakeSayHello3(ctx context.Context) GreeterStub_SayHello3 {
	rpc := channel.GetPooledRPC()

	*rpc = channel.RPC{
		Ctx:              ctx,
		ServiceID:        Greeter,
		MethodName:       Greeter_SayHello3,
		RequestExtraData: self.requestExtraData.Ref(true),
	}

	self.rpcPreparer.PrepareRPC(rpc, func() channel.Message {
		return new(SayHelloResp)
	})

	return GreeterStub_SayHello3{rpc}
}

type GreeterStub_SayHello struct {
	rpc *channel.RPC
}

func (self GreeterStub_SayHello) WithRequestExtraData(extraData channel.ExtraDataRef) GreeterStub_SayHello {
	self.rpc.RequestExtraData = extraData
	return self
}

func (self GreeterStub_SayHello) Do() GreeterStub_SayHello {
	if self.rpc.IsHandled() {
		self.rpc.Reprepare()
	}

	self.rpc.Handle()
	return self
}

func (self GreeterStub_SayHello) Result() (*SayHelloResp, error) {
	if self.rpc.Err != nil {
		return nil, self.rpc.Err
	}

	return self.rpc.Response.(*SayHelloResp), nil
}

func (self GreeterStub_SayHello) Close() {
	channel.PutPooledRPC(self.rpc)
	self.rpc = nil
}

func (self GreeterStub_SayHello) RequestExtraData() channel.ExtraDataRef {
	return self.rpc.RequestExtraData
}

func (self GreeterStub_SayHello) ResponseExtraData() channel.ExtraDataRef {
	return self.rpc.ResponseExtraData
}

type GreeterStub_SayHello2 struct {
	rpc *channel.RPC
}

func (self GreeterStub_SayHello2) WithRequestExtraData(extraData channel.ExtraDataRef) GreeterStub_SayHello2 {
	self.rpc.RequestExtraData = extraData
	return self
}

func (self GreeterStub_SayHello2) Do() GreeterStub_SayHello2 {
	if self.rpc.IsHandled() {
		self.rpc.Reprepare()
	}

	self.rpc.Handle()
	return self
}

func (self GreeterStub_SayHello2) Result() error {
	return self.rpc.Err
}

func (self GreeterStub_SayHello2) Close() {
	channel.PutPooledRPC(self.rpc)
	self.rpc = nil
}

func (self GreeterStub_SayHello2) RequestExtraData() channel.ExtraDataRef {
	return self.rpc.RequestExtraData
}

func (self GreeterStub_SayHello2) ResponseExtraData() channel.ExtraDataRef {
	return self.rpc.ResponseExtraData
}

type GreeterStub_SayHello3 struct {
	rpc *channel.RPC
}

func (self GreeterStub_SayHello3) WithRequestExtraData(extraData channel.ExtraDataRef) GreeterStub_SayHello3 {
	self.rpc.RequestExtraData = extraData
	return self
}

func (self GreeterStub_SayHello3) Do() GreeterStub_SayHello3 {
	if self.rpc.IsHandled() {
		self.rpc.Reprepare()
	}

	self.rpc.Handle()
	return self
}

func (self GreeterStub_SayHello3) Result() (*SayHelloResp, error) {
	if self.rpc.Err != nil {
		return nil, self.rpc.Err
	}

	return self.rpc.Response.(*SayHelloResp), nil
}

func (self GreeterStub_SayHello3) Close() {
	channel.PutPooledRPC(self.rpc)
	self.rpc = nil
}

func (self GreeterStub_SayHello3) RequestExtraData() channel.ExtraDataRef {
	return self.rpc.RequestExtraData
}

func (self GreeterStub_SayHello3) ResponseExtraData() channel.ExtraDataRef {
	return self.rpc.ResponseExtraData
}
